# Generated by Django 6.0.3 on 2026-04-01 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('profissional', models.CharField(max_length=100)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='app_salon_agend.servico')),
            ],
        ),
    ]
