# Generated by Django 6.0.3 on 2026-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salon_agend', '0002_calendario_diabloqueado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
