# Generated by Django 6.0.3 on 2026-04-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_salon_agend', '0003_alter_servico_duracao_alter_servico_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='duracao',
        ),
    ]
