# Generated by Django 6.0.3 on 2026-04-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salon_agend', '0004_remove_servico_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='preco',
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
